### ISSUE TITLE
Unknow error when trying to build a pdf

### ISSUE THREAD

**Issue by Julien76** [amimaro/generator-vuepress#3]
Hi,

I installed vuepress generator together with vuepress 0.14.8 globally.
I am using Windows 7.

Vuepress itself has no issue building a project. 
However, when I run the command "yo vuepress:pdf", I am getting the following error right after saying yes to the question "Generate PDF?".

Any idea what is happening?
I don't understand the error output nor what could cause the issue

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at module.exports.writing (C:\Users\ss7n1842\AppData\Roaming\npm\node_modules\generator-vuepress\generators\pdf\index.js:43:27)
    at Object.<anonymous> (C:\Users\ss7n1842\AppData\Roaming\npm\node_modules\generator-vuepress\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\ss7n1842\AppData\Roaming\npm\node_modules\generator-vuepress\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\ss7n1842\AppData\Roaming\npm\node_modules\generator-vuepress\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\ss7n1842\AppData\Roaming\npm\node_modules\generator-vuepress\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Thanks.

**Comment by amimaro** [comment]
Hi,

It's a JSON parsing error.
Your vuepress config is located at `docs/.vuepress/config.js`?
If it is, try looking for some syntax errors.
